apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres--deployment
  
spec:
  replicas: 1
  template:
    metadata:
      name: db
      labels:
        db: postgres
    spec:
      containers:
        - name: db
          image: postgres
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
          ports:
            - containerPort: 5432
  selector:
    matchLabels:
      db: postgres  