apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres--deployment
  
spec:
  replicas: 1
  template:
    name: db
    labels:
     db: postgres
  spec:
      containers:
        - name: db
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            containerPort: 5432
  selector:
    matchLabels:
      db: postgres  