apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
spec:
  replicas: 1
  template:
    metadata: 
      name: worker-app
      labels:
        app: worker
    spec:
      containers:
        - name : worker-app
          image: dockersamples/examplevotingapp_worker
  selector:
    matchLabels:
      app: worker