apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bee
  name: bee
spec:
  containers:
  - image: nginx
    name: bee
    resources: {}
  nodeSelector:
    size: large
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
